spring:
  application:
    name: 'auth-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clustehelpdesk.jdeh5sf.mongodb.net/helpdeskdb?retryWrites=true&w=majority'
      auto-index-creation: true

server:
  port: 8081