spring:
  application:
    name: 'user-service-api'
  cloud:
    config:
      uri: http://localhost:8080
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}