spring:
  application:
    name: 'user-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:help-desk-user@clustehelpdesk.jdeh5sf.mongodb.net/helpdeskdb?retryWrites=true&w=majority'
      auto-index-creation: true
springdoc:
  openapi:
    title: 'User Service API'
    description: 'Componente responsável por gerenciar usuário'
    version: '1.0.0'