version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - helpdesk

  service-discovery:
    image: jopaulo/helpdesk-service-discovery
    container_name: 'service-discovery'
    environment:
      - PORT=8761
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - helpdesk

  api-gateway:
    image: jopaulo/helpdesk-api-gateway
    container_name: 'api-gateway'
    environment:
      - SERVER_PORT=8765
      - EUREKA_URI=http://service-discovery:8761/eureka
    ports:
      - "8765:8765"
    expose:
      - 8765
    depends_on:
      - service-discovery
    networks:
      - helpdesk

  config-server:
    image: jopaulo/helpdesk-config-server
    container_name: 'config-server'
    environment:
      - CONFIG_SERVER_URI=https://github.com/jopaulomendes/help-desk-v2-config
      - CONFIG_SERVER_USERNAME=jopaulomendes
      - CONFIG_SERVER_PASSWORD=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
      - EUREKA_URI=http://service-discovery:8761/eureka
      - PORT=8888
    ports:
      - "8888:8888"
    expose:
      - 8888
    depends_on:
      - service-discovery
    networks:
      - helpdesk

  mysql:
    image: mysql:8.0.32  # Certifique-se de usar a mesma versão do MySQL Connector usado pela API
    container_name: 'mysql'  # Nome do container
    restart: always  # Reinicia o container automaticamente em caso de falhas
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: helpdesk_db  # Nome do banco de dados inicial
      MYSQL_USER: user            # Usuário adicional para a aplicação
      MYSQL_PASSWORD: password    # Senha do usuário
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Use um volume nomeado
    networks:
      - helpdesk

volumes:
  mysql_data:
    driver: local  # Usando o driver local para o volume

networks:
  helpdesk:
    driver: bridge
