spring:
  application:
    name: 'order-service-api'
  datasource:
    url: 'jdbc:mysql://mysql:3306/helpdesk_db'
    username: 'root'
    password: '1234'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  jpa:
    hibernate:
      ddl-auto: create  # Use 'update' para atualizar o esquema do banco
      dialect: org.hibernate.dialect.MySQLDialect # Dialeto para MySQL
    show-sql: true  # Opcional, para exibir as queries SQL no console
  profiles:
    active: dev